/** Common countries for enquiry forms (matches legacy site list). */
export const COUNTRIES = [
  "India",
  "United Arab Emirates",
  "United States",
  "United Kingdom",
  "Australia",
  "Canada",
  "Germany",
  "France",
  "Singapore",
  "Saudi Arabia",
  "Qatar",
  "Oman",
  "Bahrain",
  "Kuwait",
  "South Africa",
  "Belgium",
  "Poland",
  "Italy",
  "Spain",
  "Netherlands",
  "Sri Lanka",
  "Bangladesh",
  "Nepal",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Philippines",
  "Japan",
  "China",
  "Brazil",
  "Mexico",
  "Other",
] as const;
